pub const MASTER_SEED: &str = "seed1";
pub const GAME_SEED: &str = "seed2";
pub const BET_SEED: &str = "seed3";
pub const AUTHORITY: &str = "4K2dERdSDHzCM7g2h9pc82shJU4AMtvtLpa3vk3yrf8C";
pub const USDC_MINT_devnet: &str = "9gqBAKRtBHBQdTzUzH3NC1UeMPrRa6ugw56Db8cmoW5w"; //devnet token with 6 decimals
pub const USDC_MINT_localhost: &str = "5vcu7GzsAxbG7cG2r2kF2dMbd4M3MmGvZorW2RJJvSqW"; //localhost token with 6 decimals
pub const PROGRAM_ID: &str = "4karKXsd6ukYynzsuXdeojUK8MqHRfUhFkWstLzwDJ1i";
pub const RPC: &str = "https://rpc.ankr.com/solana_devnet";
pub const HOUSE_PK: &str = "";
