[features]
seeds = false
skip-lint = false
[programs.localnet]
sollounge = "8uJ5HmDKX4RtMZMyxHfQ5tF1eRt7ZaebH674xX5SoG6A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ismailhakkiodabas/Desktop/sollounge/sollounge/target/deploy/sollounge-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
